name: covid
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - scipy=1.4.1
  - numpy=1.18.1
  - pandas=1.0.3
  - dash=1.9.1
  - blas[build=openblas]
  - black
  - gunicorn=20.0.4
