name: covid
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - scipy=1.11.2
  - numpy=1.26.0
  - pandas=2.1.1
  - dash=2.13.0
  - blas[build=openblas]
  - black
  - gunicorn=21.2.0
